--- #YAML:1.0
name:               Wx
version:            0.98_01
abstract:           interface to the wxWidgets cross-platform GUI toolkit
author:
    - Mattia Barbon <mbarbon@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Alien::wxWidgets:     0.25
    Data::Dumper:         0
    ExtUtils::MakeMaker:  6.17
    ExtUtils::ParseXS:    2.2203
    ExtUtils::XSpp:       0.1601
    File::Spec::Functions:  0.82
    if:                   0.03
    Test::Harness:        2.26
    Test::More:           0.45
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
